
export CONJUR_APPLIANCE_URL=https://conjur-master
export CONJUR_ACCOUNT=conjur
export CONJUR_CERT_FILE=conjur-conjur.pem
export CONJUR_AUTHN_LOGIN=host/ansible1
export CONJUR_AUTHN_API_KEY=abksj8vn9jzm3t70nmfhcp7k1w0h59f281c5ca2c4y2nt3t5wmky
