export CONJUR_APPLIANCE_URL=https://conjur-master
export CONJUR_ACCOUNT=conjur
export CONJUR_CERT_FILE=conjur-conjur.pem
export CONJUR_AUTHN_LOGIN=host/ansible1
export CONJUR_AUTHN_API_KEY=3ht6g351zc51ez1fgw1hs3hk0d8f2mxcmev3dxj0fk2gsw5db1rdgp9v
